name        : libdmx
version     : 1.1.3
release     : 7
source      :
    - http://xorg.freedesktop.org/releases/individual/lib/libdmx-1.1.3.tar.gz : c4b24d7e13e5a67ead7a18f0b4cc9b7b5363c9d04cd01b83b5122ff92b3b4996
license     :
    - MIT
summary     : X11 Distributed Multihead extension library
component   : xorg.library
builddeps   :
    - pkgconfig(dmxproto)
    - pkgconfig(xext)
    - pkgconfig32(xext)
    - pkgconfig(x11)
    - pkgconfig32(x11)
    - glibc-32bit-devel
    - libgcc-32bit
emul32      : yes
patterns    :
    - /usr/share/man
description : |
    libdmx is an interface to the DMX extension for X, which allows a single server to be set up as a proxy spanning multiple servers -- not unlike Xinerama across discrete physical machines.  It can be reconfigured on the fly to change the layout, and it is presented as a single logical display to clients.
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
