name       : libdmx
version    : 1.1.4
release    : 8
source     :
    - https://xorg.freedesktop.org/releases/individual/lib/libdmx-1.1.4.tar.bz2 : 253f90005d134fa7a209fbcbc5a3024335367c930adf0f3203e754cf32747243
license    : MIT
component  : xorg.library
summary    : X11 Distributed Multihead extension library
description: |
    libdmx is an interface to the DMX extension for X, which allows a single server to be set up as a proxy spanning multiple servers -- not unlike Xinerama across discrete physical machines.  It can be reconfigured on the fly to change the layout, and it is presented as a single logical display to clients.
builddeps  :
    - pkgconfig(dmxproto)
    - pkgconfig32(xext)
    - pkgconfig32(x11)
    - glibc-32bit-devel
emul32     : yes
patterns   :
    - /usr/share/man
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
